['RAPGEF5', 'RAPGEF6', 'N4BP2L2', 'RAPGEF1', 'RAPGEF2', 'RAPGEF3', 'ZNF384', 'ZNF383', 'ZNF382', 'POC1B', 'MIR4420', 'KRTAP3-2', 'KRTAP3-3', 'KRTAP3-1', 'SNRPD3', 'SNRPD2', 'SNRPD1', 'GRK6', 'NMBR', 'RBM26-AS1', 'IFT43', 'IFT46', 'GLDN', 'GLDC', 'QPCT', 'PC', 'GRK5', 'DHRS11', 'DHRS12', 'DHRS13', 'GPR89B', 'GPR89C', 'GPR89A', 'MAP1LC3B2', 'LGMN', 'MIR3591', 'CAPS2', 'EHMT1', 'EHMT2', 'ADIPOR2', 'ADIPOR1', 'NBPF24', 'MARK4', 'STOX1', 'MARK1', 'MARK2', 'STOX2']
Traceback (most recent call last):
  File "coversizetestall.py", line 151, in <module>
    coverarr = dict[str(k2) + "_" + str(k1)]
KeyError: '3_3'
